url: http://www.novawebsolutions.ca

# Site settings
title: Novaweb Solutions
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Maxime Rouiller
  pic: 1
  position: President
  social:
    - title: twitter
      url: https://www.twitter.com/MaximRouiller
    - title: stack-overflow
      url: http://stackoverflow.com/users/24975/maxime-rouiller-mvp


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/NovawebSolutions

# Postal address (add as many lines as necessary)
address:
  - line: 3320 rue des Lucines
  - line: "Saint-Hubert, QC"
  - line: J3Y 0H4

# Build settings
markdown: kramdown
permalink: pretty